/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import {
  MatchResults,
} from '@stencil/router';

import {
  AppDetails as AppDetails
} from './components/app-details/app-details';

declare global {
  interface HTMLAppDetailsElement extends AppDetails, HTMLElement {
  }
  var HTMLAppDetailsElement: {
    prototype: HTMLAppDetailsElement;
    new (): HTMLAppDetailsElement;
  };
  interface HTMLElementTagNameMap {
    "app-details": HTMLAppDetailsElement;
  }
  interface ElementTagNameMap {
    "app-details": HTMLAppDetailsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-details": JSXElements.AppDetailsAttributes;
    }
  }
  namespace JSXElements {
    export interface AppDetailsAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}

